name: CI
on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    name: test (Python ${{ matrix.python-version }} on ${{ matrix.os-label }})
    strategy:
      fail-fast: false
      matrix:
        # keep it sync with tox.ini [gh-actions] section
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12-dev"]
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        include:
          - {python-version: "2.7", os: "unbuntu-20.04",}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        run: python setup.py test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

